"""
ComplianceCore AI Shared Data Models.
Defines strongly typed dataclasses for data exchange between application components.
"""

from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, List
import json

@dataclass
class CustomerProfile:
    """
    Extracted customer identity details from OCR parsing.
    """
    name: Optional[str] = None
    dob: Optional[str] = None
    address: Optional[str] = None
    pan: Optional[str] = None
    aadhaar: Optional[str] = None
    passport_number: Optional[str] = None
    driving_license_number: Optional[str] = None
    issue_date: Optional[str] = None
    expiry_date: Optional[str] = None
    utility_bill_info: Optional[str] = None
    bank_statement_info: Optional[str] = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class TransactionSummary:
    """
    Statistical aggregates and anomalies computed from transaction history.
    """
    total_transactions: int = 0
    duplicate_transactions_count: int = 0
    missing_fields_count: int = 0
    invalid_schema_count: int = 0
    high_value_transfers_count: int = 0
    repeated_beneficiaries: dict[str, int] = field(default_factory=dict)
    velocity_violations_count: int = 0
    transaction_bursts_count: int = 0
    suspicious_descriptions_count: int = 0
    cross_border_count: int = 0
    merchant_frequency: dict[str, int] = field(default_factory=dict)
    country_summary: dict[str, int] = field(default_factory=dict)
    daily_summary: dict[str, float] = field(default_factory=dict)
    average_amount: float = 0.0
    minimum_amount: float = 0.0
    maximum_amount: float = 0.0
    total_volume: float = 0.0
    findings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class RuleFinding:
    """
    Result of a single deterministic compliance rule execution.
    """
    rule_id: str
    rule_name: str
    status: str  # "PASS" or "FAIL"
    findings: str
    evidence: str
    severity: str  # "Critical", "High", "Medium", "Low", "None"
    confidence: float  # 0.0 to 1.0
    recommendation: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class RiskAssessment:
    """
    Overall computed risk score and level from deterministic findings.
    """
    risk_score: float  # 0.0 to 100.0
    risk_level: str  # "Low", "Medium", "High", "Critical"
    priority: str  # "Low", "Medium", "High", "Immediate"
    confidence: float  # 0.0 to 1.0
    findings_summary: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class GemmaResponse:
    """
    AI assessment response structure generated by Google's Gemma model.
    """
    executive_summary: str
    compliance_decision: str  # "APPROVED", "REJECTED", "ESCALATED"
    evidence: str
    severity: str  # "Critical", "High", "Medium", "Low"
    confidence: float  # 0.0 to 1.0
    audit_summary: str
    recommendations: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class AuditReport:
    """
    Metadata of a generated audit report file.
    """
    report_id: str
    generated_at: str
    pdf_path: str
    markdown_path: str
    customer_profile: CustomerProfile
    transaction_summary: TransactionSummary
    risk_assessment: RiskAssessment
    gemma_response: GemmaResponse

    def to_dict(self) -> dict:
        return {
            "report_id": self.report_id,
            "generated_at": self.generated_at,
            "pdf_path": self.pdf_path,
            "markdown_path": self.markdown_path,
            "customer_profile": self.customer_profile.to_dict(),
            "transaction_summary": self.transaction_summary.to_dict(),
            "risk_assessment": self.risk_assessment.to_dict(),
            "gemma_response": self.gemma_response.to_dict()
        }
